on:
  push:

name: test 

jobs:
  render:
    name: Run r script
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
    name: Run temp R script
    working-directory: .github/workflows
    run: Rscript -e '.github/workflows/temp.r'
