on:
  push:
    branches:
      - master

name: test 

jobs:
  render:
    name: Run r script
    runs-on: macOS-latest
    steps:
     - uses: actions/checkout@v1
     - uses: r-lib/actions/setup-r@v1
     - name: install R packages
       run: Rscript -e 'install.packages("here")'
     - name: Run temp R script
       run: Rscript -e './temp.r'
