on:
  push:
    branches:
      - master

name: test 

jobs:
  render:
    name: Run r script
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - uses: r-lib/actions/setup-r@v1
     - name: install R packages
       run: Rscript -e 'install.packages("here")'
     - name: source a temp R script 
       run: Rscript -e 'source("temp.r")'
     - name: render R-markdown to regular R-markdown
       run: Rscript -e 'knitr::knit("paper1.Rmd", output = "paper1.md")'
       
